"""Tools for dynamical-systems inspired econometric rare-event analysis."""

from dynsys_econometrics.data import (
    DataLoadFailure,
    load_ecb_sdw_csv,
    load_fred,
    load_fred_csv,
    load_oecd_csv,
    load_time_series_csv,
    load_world_bank_csv,
    load_yfinance_series,
)
from dynsys_econometrics.extremes import (
    ExceedanceExtractionResult,
    ExtremalIndexResult,
    ThresholdSensitivityResult,
    block_maxima,
    estimate_cluster_size_extremal_index,
    estimate_extremal_index,
    estimate_runs_extremal_index,
    extract_threshold_exceedances,
    peaks_over_threshold,
    runs_declustering,
    runs_declustering_from_indicator,
    threshold_sensitivity_analysis,
)
from dynsys_econometrics.return_times import (
    ExponentialComparisonResult,
    ReturnTimeDistribution,
    compute_return_times,
    empirical_survival_curve,
    exponential_benchmark_comparison,
    first_hitting_time,
    ks_exponential_diagnostic,
    return_time_distribution,
)
from dynsys_econometrics.simulation import (
    logistic_map,
    simulate_ar1,
    simulate_coupled_logistic_maps,
    simulate_garch11,
    simulate_iid_gaussian,
    simulate_pomeau_manneville,
    simulate_student_t,
)

__all__ = [
    "DataLoadFailure",
    "ExponentialComparisonResult",
    "ReturnTimeDistribution",
    "ThresholdSensitivityResult",
    "compute_return_times",
    "ExceedanceExtractionResult",
    "ExtremalIndexResult",
    "empirical_survival_curve",
    "estimate_cluster_size_extremal_index",
    "estimate_extremal_index",
    "estimate_runs_extremal_index",
    "exponential_benchmark_comparison",
    "extract_threshold_exceedances",
    "first_hitting_time",
    "ks_exponential_diagnostic",
    "load_ecb_sdw_csv",
    "load_fred",
    "load_fred_csv",
    "load_oecd_csv",
    "load_time_series_csv",
    "load_world_bank_csv",
    "load_yfinance_series",
    "logistic_map",
    "peaks_over_threshold",
    "return_time_distribution",
    "runs_declustering",
    "runs_declustering_from_indicator",
    "simulate_ar1",
    "simulate_coupled_logistic_maps",
    "simulate_garch11",
    "simulate_iid_gaussian",
    "simulate_pomeau_manneville",
    "simulate_student_t",
    "threshold_sensitivity_analysis",
    "block_maxima",
]
