"""Tools for dynamical-systems inspired econometric rare-event analysis."""

from dynsys_econometrics.baselines import (
    autocorrelation_summary,
    drawdown_series,
    regime_summary,
    rolling_volatility,
)
from dynsys_econometrics.config import load_config, resolve_output_dir
from dynsys_econometrics.contracts import EventFrame, ExperimentResult, TimeSeriesFrame
from dynsys_econometrics.data import (
    DataLoadFailure,
    load_ecb_sdw_csv,
    load_empirical_panel,
    load_fred,
    load_fred_csv,
    load_oecd_csv,
    load_panel_from_directory,
    load_time_series_csv,
    load_timeseries_csv,
    load_world_bank_csv,
    load_yfinance_series,
    materialize_catalog,
    validate_catalog,
    write_processed_panel,
)
from dynsys_econometrics.econometrics import compare_event_diagnostics
from dynsys_econometrics.experiments import (
    run_empirical_experiment,
    run_synthetic_experiment,
    save_experiment_result,
)
from dynsys_econometrics.extremes import (
    ExceedanceExtractionResult,
    ExtremalIndexResult,
    ThresholdSensitivityResult,
    assign_runs,
    block_maxima,
    estimate_cluster_size_extremal_index,
    estimate_extremal_index,
    estimate_runs_extremal_index,
    extract_threshold_exceedances,
    mean_excess_table,
    peaks_over_threshold,
    runs_declustering,
    runs_declustering_from_indicator,
    runs_extremal_index,
    threshold_exceedances,
    threshold_sensitivity_analysis,
)
from dynsys_econometrics.multivariate import (
    joint_exceedances,
    stress_state_index,
    tail_dependence_coefficient,
    wide_panel,
)
from dynsys_econometrics.return_times import (
    ExponentialComparisonResult,
    ReturnTimeDistribution,
    compare_return_time_distributions,
    compute_return_times,
    empirical_survival_curve,
    exponential_benchmark_comparison,
    first_hitting_time,
    inter_event_durations,
    ks_exponential_diagnostic,
    recurrence_rate,
    return_time_distribution,
    return_times,
    survival_curve,
)
from dynsys_econometrics.simulation import (
    logistic_map,
    simulate_ar1,
    simulate_coupled_logistic_maps,
    simulate_garch11,
    simulate_iid_gaussian,
    simulate_intermittent_map,
    simulate_logistic_map,
    simulate_pomeau_manneville,
    simulate_student_t,
)
from dynsys_econometrics.transforms import pct_change, standardize_panel, winsorize_series
from dynsys_econometrics.transforms import log_returns, rolling_zscore
from dynsys_econometrics.utils import ensure_directory, repo_root, write_json

__all__ = [
    "EventFrame",
    "ExperimentResult",
    "TimeSeriesFrame",
    "DataLoadFailure",
    "ExponentialComparisonResult",
    "ReturnTimeDistribution",
    "ThresholdSensitivityResult",
    "assign_runs",
    "autocorrelation_summary",
    "compare_event_diagnostics",
    "compare_return_time_distributions",
    "compute_return_times",
    "ExceedanceExtractionResult",
    "ExtremalIndexResult",
    "empirical_survival_curve",
    "ensure_directory",
    "estimate_cluster_size_extremal_index",
    "estimate_extremal_index",
    "estimate_runs_extremal_index",
    "exponential_benchmark_comparison",
    "extract_threshold_exceedances",
    "first_hitting_time",
    "inter_event_durations",
    "joint_exceedances",
    "ks_exponential_diagnostic",
    "load_config",
    "load_ecb_sdw_csv",
    "load_empirical_panel",
    "load_fred",
    "load_fred_csv",
    "load_oecd_csv",
    "load_panel_from_directory",
    "load_time_series_csv",
    "load_timeseries_csv",
    "load_world_bank_csv",
    "load_yfinance_series",
    "materialize_catalog",
    "logistic_map",
    "mean_excess_table",
    "peaks_over_threshold",
    "pct_change",
    "recurrence_rate",
    "regime_summary",
    "repo_root",
    "resolve_output_dir",
    "rolling_volatility",
    "run_empirical_experiment",
    "run_synthetic_experiment",
    "return_time_distribution",
    "return_times",
    "runs_declustering",
    "runs_declustering_from_indicator",
    "runs_extremal_index",
    "save_experiment_result",
    "simulate_ar1",
    "simulate_coupled_logistic_maps",
    "simulate_garch11",
    "simulate_iid_gaussian",
    "simulate_intermittent_map",
    "simulate_logistic_map",
    "simulate_pomeau_manneville",
    "simulate_student_t",
    "standardize_panel",
    "stress_state_index",
    "survival_curve",
    "tail_dependence_coefficient",
    "threshold_exceedances",
    "threshold_sensitivity_analysis",
    "validate_catalog",
    "wide_panel",
    "winsorize_series",
    "write_json",
    "write_processed_panel",
    "block_maxima",
]
